name: Build and Deploy to Azure Blob Storage

on:
  push:
    branches: [ main, master ]  # Déclenche le workflow sur les push vers main/master
  workflow_dispatch:            # Permet l'exécution manuelle depuis l'interface GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout du code source
      - uses: actions/checkout@v3

      # Configuration de Node.js
      - name: Build & Publish to blob storage
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Utiliser la version de Node appropriée pour votre projet
          cache: 'npm'

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Installation des dépendances
      - name: Install dependencies
        run: npm ci

      # Build du projet
      - name: Build project
        run: npm run build

      # Build du DSP
      - name: Build project
        run: npm run build:dsp

      # Déployer vers Azure Blob Storage
      - name: Deploy to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: build
          container_name: $web
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          overwrite: 'true'
